## 0. Entorno

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import plotly.express as px
import plotly.io as pio
import mysql.connector

In [3]:
import os
os.getcwd()

'/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-'

## 1. Exploración de datos

In [4]:
#carga CSVs
agric = pd.read_csv('/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/data/FAOSTAT_data_es_6-11-2026.csv')

In [5]:
clima = pd.read_csv(
    '/Users/rosamariasierraalmeria/Documents/GitHub/Impacto-del-clima-en-la-agricultura-/data/POWER_Point_Monthly_20050101_20241231_040d42N_003d70W_LST.csv',
    skiprows=13,
    na_values=['-999', '-999.0']
)

In [6]:
#Resumen y comprobación de la correcta carga de datos 'agric'
agric.head()

,Código del ámbito,Ámbito,Código del área (M49),Área,Código del elemento,Elemento,Código del producto (CPC),Producto,Código del año,Año,Unidad,Valor,Símbolo,Descripción del Símbolo,Nota
0,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2005,2005,toneladas,6300.0,X,Cifra de fuente externa,Cifras no oficiales
1,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2006,2006,toneladas,34300.0,X,Cifra de fuente externa,Cifras no oficiales
2,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2007,2007,toneladas,28700.0,X,Cifra de fuente externa,Cifras no oficiales
3,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2008,2008,toneladas,37300.0,X,Cifra de fuente externa,Cifras no oficiales
4,QCL,Cultivos y productos de ganadería,724,España,5510,Producción,21641.01,"Aceite de colza, en bruto",2009,2009,toneladas,42600.0,X,Cifra de fuente externa,Cifras no oficiales

In [7]:
agric.info()

<class 'pandas.DataFrame'>
RangeIndex: 5904 entries, 0 to 5903
Data columns (total 15 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Código del ámbito          5904 non-null   str
 1   Ámbito                     5904 non-null   str
 2   Código del área (M49)      5904 non-null   int64
 3   Área                       5904 non-null   str
 4   Código del elemento        5904 non-null   int64
 5   Elemento                   5904 non-null   str
 6   Código del producto (CPC)  5904 non-null   str
 7   Producto                   5904 non-null   str
 8   Código del año             5904 non-null   int64
 9   Año                        5904 non-null   int64
 10  Unidad                     5904 non-null   str
 11  Valor                      5823 non-null   float64
 12  Símbolo                    5904 non-null   str
 13  Descripción del Símbolo    5904 non-null   str
 14  Nota                       210 non-null    str
dtypes: float64(1), int64(4), str(10)
memory usage: 692.0 KB

In [8]:
clima.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   PARAMETER  100 non-null    str
 1   YEAR       100 non-null    int64
 2   JAN        100 non-null    float64
 3   FEB        100 non-null    float64
 4   MAR        100 non-null    float64
 5   APR        100 non-null    float64
 6   MAY        100 non-null    float64
 7   JUN        100 non-null    float64
 8   JUL        100 non-null    float64
 9   AUG        100 non-null    float64
 10  SEP        100 non-null    float64
 11  OCT        100 non-null    float64
 12  NOV        100 non-null    float64
 13  DEC        100 non-null    float64
 14  ANN        100 non-null    float64
dtypes: float64(13), int64(1), str(1)
memory usage: 11.8 KB

In [9]:
#Resumen y comprobación de la correcta carga de datos 'clima'
clima.head()

,PARAMETER,YEAR,JAN,FEB,MAR,APR,MAY,JUN,JUL,AUG,SEP,OCT,NOV,DEC,ANN
0,PRECTOTCORR,2005,0.08,1.34,0.60,0.84,0.62,0.73,0.01,0.18,0.28,3.19,1.89,1.09,0.90
1,PRECTOTCORR,2006,1.00,1.61,1.33,1.04,0.65,1.21,0.10,0.35,0.75,3.48,3.59,0.95,1.33
2,PRECTOTCORR,2007,0.64,1.77,0.81,2.56,3.00,1.29,0.04,0.46,0.40,1.60,1.17,0.51,1.18
3,PRECTOTCORR,2008,0.86,1.00,0.47,2.52,3.22,1.29,0.38,0.03,1.27,3.73,0.64,1.83,1.44
4,PRECTOTCORR,2009,1.57,1.52,0.70,1.13,0.79,0.54,0.01,0.19,0.39,1.28,0.73,3.34,1.02

In [10]:
agric.columns

Index(['Código del ámbito', 'Ámbito', 'Código del área (M49)', 'Área',
       'Código del elemento', 'Elemento', 'Código del producto (CPC)',
       'Producto', 'Código del año', 'Año', 'Unidad', 'Valor', 'Símbolo',
       'Descripción del Símbolo', 'Nota'],
      dtype='str')

In [11]:
clima.columns

Index(['PARAMETER', 'YEAR', 'JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL',
       'AUG', 'SEP', 'OCT', 'NOV', 'DEC', 'ANN'],
      dtype='str')

In [12]:
#Gestión de nulos 'agric'
(agric.isnull().sum()/len(agric))*100

Código del ámbito             0.000000
Ámbito                        0.000000
Código del área (M49)         0.000000
Área                          0.000000
Código del elemento           0.000000
Elemento                      0.000000
Código del producto (CPC)     0.000000
Producto                      0.000000
Código del año                0.000000
Año                           0.000000
Unidad                        0.000000
Valor                         1.371951
Símbolo                       0.000000
Descripción del Símbolo       0.000000
Nota                         96.443089
dtype: float64

In [13]:
#Gestión de nulos 'clima'
(clima.isnull().sum()/len(agric))*100

PARAMETER    0.0
YEAR         0.0
JAN          0.0
FEB          0.0
MAR          0.0
APR          0.0
MAY          0.0
JUN          0.0
JUL          0.0
AUG          0.0
SEP          0.0
OCT          0.0
NOV          0.0
DEC          0.0
ANN          0.0
dtype: float64

In [14]:
#Revisión de datos únicos de ambos CSV
print(agric['Producto'].unique())

<StringArray>
[          'Aceite de colza, en bruto',         'Aceite de girasol, en bruto',
                     'Aceite, algodón',           'Aceite, almendra de palma',
             'Aceite, cártamo, alazor',                       'Aceite, copra',
                      'Aceite, linaza',                        'Aceite, maíz',
                       'Aceite, oliva',                        'Aceite, soja',
 ...
                 'Tabaco sin elaborar', 'Tangerinas, mandarinas, clementinas',
                    'Tomates, frescos',                               'Trigo',
                           'Triticale',                          'Uva espina',
                                'Uvas',                                'Veza',
                                'Vino',                  'Zanahorias y nabos']
Length: 124, dtype: str

In [15]:
print(agric['Unidad'].unique())

<StringArray>
['toneladas', 'ha', 'kg/ha']
Length: 3, dtype: str

In [16]:
#Verificación y creación de índices en ambos CSVs
print(agric.index.name)

None

In [17]:
print(clima.index.name)

None

In [18]:
agric.index.name = 'Agric_ID'

In [19]:
print(agric.index.name)

Agric_ID

In [20]:
clima.index.name = 'Clima_ID'

In [21]:
print(clima.index.name)

Clima_ID

## 2. Creación y carga de tablas en SQL

### 2.1 Esquema de las tablas

```sql
CREATE TABLE Agricultura (
    AgriculturaID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CodigoAmbito VARCHAR(50),
    Ambito VARCHAR(100),
    CodigoAreaM49 INT,
    Area VARCHAR(100),
    CodigoElemento INT,
    Elemento VARCHAR(100),
    CodigoProductoCPC VARCHAR(50),
    Producto VARCHAR(200),
    CodigoAnio INT,
    Anio INT,
    Unidad VARCHAR(50),
    Valor DECIMAL(18,4),
    Simbolo VARCHAR(20),
    DescripcionSimbolo VARCHAR(255),
    Nota TEXT
);

CREATE TABLE Clima (
    ClimaID BIGINT AUTO_INCREMENT PRIMARY KEY,
    Parameter VARCHAR(50),
    Year INT,
    Jan DECIMAL(10,4),
    Feb DECIMAL(10,4),
    Mar DECIMAL(10,4),
    Apr DECIMAL(10,4),
    May DECIMAL(10,4),
    Jun DECIMAL(10,4),
    Jul DECIMAL(10,4),
    Aug DECIMAL(10,4),
    Sep DECIMAL(10,4),
    Oct DECIMAL(10,4),
    Nov DECIMAL(10,4),
    Dec DECIMAL(10,4),
    Ann DECIMAL(10,4)
);
```